import argparse
import json
import subprocess
import sys
from pathlib import Path
import os
os.environ["VLLM_LOGGING_LEVEL"] = "WARNING"
import logging

# Aggiungi questo nel tuo main() prima di chiamare il generatore
logging.getLogger("vllm").setLevel(logging.WARNING)
logging.getLogger("vllm.model_executor.layers.linear").setLevel(logging.WARNING)

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
TEXT_TO_SQL_ROOT = PROJECT_DIR.parent
AUTOKG_ROOT = TEXT_TO_SQL_ROOT / "autoKG"

DESCRIPTIONS_DIR = PROJECT_DIR / "descriptions"
AUTOKG_INPUT_DIR = PROJECT_DIR / "auto_kg_input"
AUTOKG_OUTPUT_DIR = PROJECT_DIR / "auto_kg_output"
AUTOKG_RUNNER = AUTOKG_ROOT / "script" / "_2_run_schema_induction.py"


def extract_db_name(description_path: Path) -> str:
    name = description_path.name
    suffix = ".semantic_evidence.txt"
    if name.endswith(suffix):
        return name[: -len(suffix)]
    return description_path.stem


def build_autokg_record(description_path: Path) -> list[dict]:
    db_name = extract_db_name(description_path)
    text = description_path.read_text(encoding="utf-8").strip()
    if not text:
        raise ValueError(f"Description file is empty: {description_path}")

    return [
        {
            "id": db_name,
            "text": text,
            "metadata": {"lang": "en"},
        }
    ]


def prepare_autokg_inputs(
    descriptions_dir: Path,
    output_dir: Path,
    target_db: str | None = None,
) -> list[str]:
    output_dir.mkdir(parents=True, exist_ok=True)

    description_files = sorted(descriptions_dir.glob("*.txt"))
    
    if target_db:
        description_files = [
            path for path in description_files if extract_db_name(path) == target_db
        ]
        
    if not description_files:
        raise FileNotFoundError(
            f"No description files found in '{descriptions_dir}' for target '{target_db}'."
        )

    prepared_db_names: list[str] = []
    for description_path in description_files:
        db_name = extract_db_name(description_path)
        records = build_autokg_record(description_path)
        output_path = output_dir / f"{db_name}.json"
        output_path.write_text(
            json.dumps(records, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        prepared_db_names.append(db_name)
        print(f"[prepare] Wrote AutoKG input: {output_path}")

    return prepared_db_names

def run_autokg(
    db_name: str,
    model_path: str | None,
    logical_model_name: str | None,
    input_dir: Path,
    output_dir: Path,
    batch_size_triple: int,
    batch_size_concept: int,
    max_new_tokens: int,
) -> None:
    # Se non è stato passato esplicitamente un nome logico, proviamo a ricavarlo o usiamo un default
    if not logical_model_name:
        logical_model_name = "Unknown model"

    command = [
        sys.executable,
        str(AUTOKG_RUNNER),
        "--keyword",
        db_name,
        "--input-dir",
        str(input_dir),
        "--output-dir",
        str(output_dir),
        "--batch-size-triple",
        str(batch_size_triple),
        "--batch-size-concept",
        str(batch_size_concept),
        "--max-new-tokens",
        str(max_new_tokens),
        "--model",
        str(logical_model_name)
    ]

    if model_path:
        command.extend(["--model-path", model_path])

    print(f"[autokg] Running for database: {db_name}")
    print(f"[autokg] Labeling run output as logical model: {logical_model_name}")
    print(f"[autokg] Command: {' '.join(command)}")
    
    try:
        result = subprocess.run(
            command, 
            check=True, 
            cwd=AUTOKG_ROOT,
            capture_output=True,
            text=True
        )
        if result.stdout:
            print(result.stdout)
    except subprocess.CalledProcessError as exc:
        print("\n" + "="*60)
        print(f"[CRITICAL ERROR] AutoKG runner failed for {db_name}!")
        print(f"Exit Code: {exc.returncode}")
        print("-"*60)
        print("STDOUT DELL'ERRORE:")
        print(exc.stdout)
        print("-"*60)
        print("STDERR DELL'ERRORE (Traceback reale):")
        print(exc.stderr)
        print("="*60 + "\n")
        raise exc

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare AutoKG inputs from DB descriptions and run AutoKG extraction."
    )
    parser.add_argument(
        "--db-name",
        default=None,
        help="Run only for one database name. If omitted, process only the first database for testing.",
    )
    parser.add_argument(
        "--descriptions-dir",
        type=Path,
        default=DESCRIPTIONS_DIR,
        help="Directory containing DB descriptions generated by _2_generate_db_descriptions.py",
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=AUTOKG_INPUT_DIR,
        help="Directory where AutoKG-formatted JSON inputs will be written.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=AUTOKG_OUTPUT_DIR,
        help="Directory where AutoKG outputs will be written.",
    )
    parser.add_argument(
        "--model-path",
        type=str,
        default=None,
        help="Optional local model path forwarded to autoKG.",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Logical model name to label the run output in AutoKG (e.g. Qwen3.6-27B).",
    )
    parser.add_argument(
        "--batch-size-triple",
        type=int,
        default=8,
        help="Batch size for triple extraction.",
    )
    parser.add_argument(
        "--batch-size-concept",
        type=int,
        default=8,
        help="Batch size for concept generation.",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=8192,
        help="Maximum generation length passed to AutoKG.",
    )
    parser.add_argument(
        "--prepare-only",
        action="store_true",
        help="Only prepare AutoKG input JSON files, without running AutoKG.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if not AUTOKG_ROOT.exists():
        raise FileNotFoundError(f"AutoKG root not found: {AUTOKG_ROOT}")
    if not AUTOKG_RUNNER.exists():
        raise FileNotFoundError(f"AutoKG runner not found: {AUTOKG_RUNNER}")

    db_names = prepare_autokg_inputs(
        descriptions_dir=args.descriptions_dir,
        output_dir=args.input_dir,
        target_db=args.db_name,
    )

    if args.prepare_only:
        print("[done] AutoKG inputs prepared only.")
        return

    args.output_dir.mkdir(parents=True, exist_ok=True)
    for db_name in db_names:
        run_autokg(
            db_name=db_name,
            model_path=args.model_path,
            logical_model_name=args.model,
            input_dir=args.input_dir,
            output_dir=args.output_dir,
            batch_size_triple=args.batch_size_triple,
            batch_size_concept=args.batch_size_concept,
            max_new_tokens=args.max_new_tokens,
        )

    print("[done] AutoKG pipeline completed.")


if __name__ == "__main__":
    main()